### ISSUE TITLE
Attach loading bar to custom DOM node

### ISSUE THREAD

**Issue by j4mesjung** [skt-t1-byungi/rsup-progress#4]
I really like this library!  Great job.
I am trying to use this for a project but instead of the loading bar being fixed to the top, is there a way to mount the progress bar to a specific DOM node?

**Comment by skt-t1-byungi** [comment]
```css

**Comment by skt-t1-byungi** [comment]
Thanks for the compliment.
There is currently no way.  Why do you want that? I want to keep the api as simple. 
If you want to change the fixed position, you can do the following:

```js
// js
const progress = new RsupProgress({ className: 'bar' })
```
```css
/* css */
.bar{ bottom: 0; top: unset!important; }
```

**Comment by j4mesjung** [comment]
One use case is that I wanted to have this loading bar in a popup Modal I was rendering.  I think having it so that a developer can specify an element to mount this on would be a good option.  

For some context, I was trying to implement this in my React project.  Maybe I'll fork this repo and try to create a React component for this so that I can slap something like `<Progress` anywhere in the dom.

**Comment by skt-t1-byungi** [comment]
I have accepted your suggestion. From now, it can be done with the `container` option.
Thanks for the idea.

**Comment by j4mesjung** [comment]
Thank you!
