### ISSUE TITLE
Inline documentation

### ISSUE THREAD

**Issue by ghost** [skt-t1-byungi/rsup-progress#5]
JSDoc or TSDoc

**Comment by skt-t1-byungi** [comment]
Um ... I think typescript's type is enough.

**Comment by ghost** [comment]
😱😯

**Comment by skt-t1-byungi** [comment]
This is probably a personal dislike.

I don't like increasing the need to sync with the same content (typescript type and readme).
It's verbose and sometimes makes mismatches.

In JavaScript, I might have considered jsdoc. But I don't know if it's necessary even in the typescript.
